apiVersion: v1
data:
  policy.csv: |
    p, readonly, applications, get, */*, allow
    p, role:read-only, applications, list, */*, allow
    g, newuser, role:readonly
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"policy.csv":"p, readonly, applications, get, */*, allow\np, role:read-only, applications, list, */*, allow\ng, newuser, role:readonly\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2024-10-29T06:58:25Z","labels":{"app.kubernetes.io/name":"argocd-rbac-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-rbac-cm","namespace":"argocd","resourceVersion":"31322","uid":"5bc9c934-fe2f-4f5e-a431-8031fc14fbc2"}}
  creationTimestamp: "2024-10-29T06:58:25Z"
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd
  resourceVersion: "32094"
  uid: 5bc9c934-fe2f-4f5e-a431-8031fc14fbc2
