services:
  web-app:
    image: matankaufman/web-app:latest
    ports:
      - "5000"
    deploy:
      mode: replicated
      replicas: 3

  web-nginx:
    image: nginx:latest
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
    - web-app
    ports:
    - "9000:9090"

