name: GitOpd-argoCD
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Fetch Git tags
        run: git fetch --tags

      - name: Tag version
        id: version
        uses: bitshifted/git-auto-semver@v1
        with:
          main_branch: main
          create_tag: true
          tag_prefix: v

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to Docker-Hub
        uses: docker/build-push-action@v3
        with:
          context: web-app/.
          push: true
          tags: matankaufman/web-app:${{ steps.version.outputs.version-string }}

