apiVersion: v1
data:
  accounts.newuser: login
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"accounts.newuser":"login"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2024-10-29T06:58:25Z","name":"argocd-cm","namespace":"argocd","resourceVersion":"29041","uid":"a4810235-8c47-432c-8ea5-477de17e2fa6"}}
  creationTimestamp: "2024-10-29T06:58:25Z"
  name: argocd-cm
  namespace: argocd
  resourceVersion: "30426"
  uid: a4810235-8c47-432c-8ea5-477de17e2fa6
