apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    p, reader-user, applications, get, */*, allow
    g, reader-user, role:readonly
    accounts.reader-user: apiKey,login
  scopes: '[groups, email]'
