apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"policy.csv":"p, reader-user, applications, get, */*, allow\n","scopes":"[groups, email]"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"argocd-rbac-cm","namespace":"argocd"}}
  creationTimestamp: "2024-10-29T06:58:25Z"
  name: argocd-rbac-cm
  namespace: argocd
  resourceVersion: "29042"
  uid: 5bc9c934-fe2f-4f5e-a431-8031fc14fbc2
data:
  policy.csv: |
    p, readonly, applications, get, */*, allow
    p, role:read-only, applications, list, */*, allow
    g, newuser, role:readonly

