apiVersion: v1
kind: Service
metadata:
  labels:
    app: weather-app
  name: weather-app
  namespace: argocd
spec:
  clusterIP: 10.107.251.113
  clusterIPs:
  - 10.107.251.113
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30857
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: weather-app
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
