apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-10-29T09:57:07Z"
  labels:
    app: weather-app
  name: weather-app
  namespace: argocd
  resourceVersion: "9780"
  uid: 365b8b96-64f3-42a2-a8c8-f6a12106b169
spec:
  clusterIP: 10.107.251.113
  clusterIPs:
  - 10.107.251.113
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30857
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: weather-app
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
