apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2024-10-29T09:48:43Z"
  generation: 1
  labels:
    app: weather-app
  name: weather-app
  namespace: argocd
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: weather-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
      - image: matankaufman/web-app:1.0.14
        imagePullPolicy: IfNotPresent
        name: web-app
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
